### PR TITLE
modernize recipe and add maintainer

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@conda-forge/core since @pmlandwehr has been inactive on CF since a while, can someone please merge so I can refresh this feedstock? Thank you. @pmlandwehr if you have anything against this, let me know! :wink:

**Review by mbargull — APPROVED** [review]
LGTM! Thanks @carlodri for taking this on!

**Comment by mbargull** [comment]
@conda-forge-admin, please update team

**Pull request merged**
